apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namePrefix: notebook-controller-
namespace: default
patchesStrategicMerge:
- deployment_patch.yaml
commonLabels:
  app: notebook-controller
  kustomize.component: notebook-controller
images:
- name: apache/submarine
  newName: apache/submarine
  newTag: notebook-controller-v1.1.0-g253890cb
configMapGenerator:
- name: parameters
  literals:
    - USE_ISTIO=false
    - ISTIO_GATEWAY=
generatorOptions:
  disableNameSuffixHash: true
vars:
- fieldref:
    fieldPath: data.USE_ISTIO
  name: USE_ISTIO
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.ISTIO_GATEWAY
  name: ISTIO_GATEWAY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
